{% set name = "mpb" %}
{% set version = "1.11.0" %}
{% set sha256 = "5852a0a40cd035ffcbab9cfdab759be731bfe1d9c8cc491120acbac26731d4a0" %}
{% set buildnumber = 12 %}

# recipe-lint fails if mpi is undefined
{% set mpi = mpi or 'nompi' %}
{% if mpi == "nompi" %}
# prioritize nompi via build number
{% set buildnumber = buildnumber + 100 %}
{% endif %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/NanoComp/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ buildnumber }}
  skip: true  # [win]
  {% if mpi != "nompi" %}
  {% set mpi_prefix = "mpi_" + mpi %}
  {% else %}
  {% set mpi_prefix = "nompi" %}
  {% endif %}
  # add build string so packages can depend on
  # mpi or nompi variants
  # dependencies:
  # `mpb * mpi_mpich_*` for mpich
  # `mpb * mpi_*` for any mpi
  # `mpb * nompi_*` for no mpi
  string: {{ mpi_prefix }}_h{{ PKG_HASH }}_{{ buildnumber }}
  run_exports:
    - {{ name }} * {{ mpi_prefix }}_*

requirements:
  build:
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - make
  host:
    - {{ mpi }}  # [mpi != 'nompi']
    - libblas
    - libcblas
    - liblapack
    - fftw
    - hdf5 1.10.5
    - libctl >=4.5.0
  run:
    - {{ mpi }}  # [mpi != 'nompi']
    - fftw
    - hdf5 1.10.5
    - libctl >=4.5.0
    - zlib
    - _openmp_mutex  # [linux]

test:
  commands:
    - test -f ${PREFIX}/lib/libmpb${SHLIB_EXT}

about:
  home: https://github.com/NanoComp/mpb
  license: GPL-2.0-or-later
  license_file: COPYING
  summary: MIT Photonic-Bands - computation of photonic band structures in periodic media
  doc_url: https://mpb.readthedocs.io
  dev_url: https://github.com/NanoComp/mpb

extra:
  recipe-maintainers:
    - ChristopherHogan
    - oskooi
    - RobinD42
