{% set name = "mpb" %}
{% set version = "1.6.2" %}
{% set sha256 = "aae270f9f51e7ff852fe578b8ef775b22489d4198f6a35ee0a91a60548fd1e3a" %}

package:
  name: {{ name }}
  version: {{version}}

source:
  fn: {{ name }}-{{version}}.tar.gz
  url: https://github.com/stevengj/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - openblas 0.2.20|0.2.20.*
    - gcc
    - fftw
    - hdf5 1.10.1
    - libctl >=4.0.0
  run:
    - openblas 0.2.20|0.2.20.*
    - fftw
    - hdf5 1.10.1
    - libgfortran
    - libgcc
    - libctl >=4.0.0

test:
  commands:
    - test -f ${PREFIX}/lib/libmpb${SHLIB_EXT}

about:
  home: http:/github.com/stevengj/mpb
  license: GPL-2.0
  license_file: COPYING
  summary: MIT Photonic-Bands - computation of photonic band structures in periodic media
  doc_url: http://mpb.readthedocs.io
  dev_url: https://github.com/stevengj/mpb

extra:
  recipe-maintainers:
    - ChristopherHogan
